# permissions for end users to view ephemeralresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: ephemeralresource-viewer-role
rules:
- apiGroups:
  - core.core.ephemeral.io
  resources:
  - ephemeralresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.core.ephemeral.io
  resources:
  - ephemeralresources/status
  verbs:
  - get
